import { CompressionRule } from '../../core/types';

export const actionRules: CompressionRule[] = [
  {
    id: 'action-help-me-refactor',
    category: 'action',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bhelp me (?:to\s+)?refactor\b/gi,
    replacement: 'refactor',
    enabled: true,
    description: 'Shorten "help me refactor"',
  },
  {
    id: 'action-help-me-fix',
    category: 'action',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bhelp me (?:to\s+)?fix\b/gi,
    replacement: 'fix',
    enabled: true,
    description: 'Shorten "help me fix"',
  },
  {
    id: 'action-help-me-write',
    category: 'action',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bhelp me (?:to\s+)?write\b/gi,
    replacement: 'write',
    enabled: true,
    description: 'Shorten "help me write"',
  },
  {
    id: 'action-help-me-create',
    category: 'action',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bhelp me (?:to\s+)?create\b/gi,
    replacement: 'create',
    enabled: true,
    description: 'Shorten "help me create"',
  },
  {
    id: 'action-help-me-implement',
    category: 'action',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bhelp me (?:to\s+)?implement\b/gi,
    replacement: 'implement',
    enabled: true,
    description: 'Shorten "help me implement"',
  },
  {
    id: 'action-cleaner-and-easier',
    category: 'action',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bcleaner and easier to read\b/gi,
    replacement: 'more readable',
    enabled: true,
    description: 'Shorten "cleaner and easier to read"',
  },
  {
    id: 'action-explain-the-changes',
    category: 'action',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bexplain the changes before (?:giving|providing) the (?:final\s+)?code\b/gi,
    replacement: 'explain before code',
    enabled: true,
    description: 'Compress "explain the changes before giving the code"',
  },
  {
    id: 'action-as-concise-as-possible',
    category: 'action',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bas concise(?:ly)? as possible\b/gi,
    replacement: 'concisely',
    enabled: true,
    description: 'Shorten "as concisely as possible"',
  },
  {
    id: 'action-make-it-cleaner',
    category: 'action',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'aggressive',
    pattern: /\bmake it (?:more\s+)?(?:clean(?:er)?|readable|maintainable)\b/gi,
    replacement: 'improve readability',
    enabled: true,
    description: 'Compress "make it cleaner/readable/maintainable"',
  },
  {
    id: 'action-the-following',
    category: 'action',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'aggressive',
    pattern: /\bthe following\b/gi,
    replacement: 'this',
    enabled: true,
    description: 'Replace "the following" with "this"',
  },
];
