import { CompressionRule } from '../../core/types';

export const constraintRules: CompressionRule[] = [
  {
    id: 'constraint-do-not-change',
    category: 'constraint',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bdo not change\b/gi,
    replacement: "don't change",
    enabled: true,
    description: 'Shorten "do not change"',
  },
  {
    id: 'constraint-do-not-modify',
    category: 'constraint',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bdo not modify\b/gi,
    replacement: "don't modify",
    enabled: true,
    description: 'Shorten "do not modify"',
  },
  {
    id: 'constraint-do-not-add',
    category: 'constraint',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bdo not add\b/gi,
    replacement: 'no new',
    enabled: true,
    description: 'Shorten "do not add"',
  },
  {
    id: 'constraint-preserve-behavior',
    category: 'constraint',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\b(?:keep|preserve|maintain) the (?:same\s+)?(?:existing\s+)?behavior\b/gi,
    replacement: 'preserve behavior',
    enabled: true,
    description: 'Compress "keep/preserve the behavior"',
  },
  {
    id: 'constraint-no-dependencies',
    category: 'constraint',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bdo not add any (?:new\s+)?(?:external\s+)?dependencies\b/gi,
    replacement: 'no new deps',
    enabled: true,
    description: 'Compress "do not add any dependencies"',
  },
  {
    id: 'constraint-without-breaking',
    category: 'constraint',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bwithout breaking (?:any(?:thing)?|existing)\b/gi,
    replacement: 'without breaking',
    enabled: true,
    description: 'Compress "without breaking anything"',
  },
  {
    id: 'constraint-backward-compat',
    category: 'constraint',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bbackward[s]?[\s-]?compatible\b/gi,
    replacement: 'backward-compatible',
    enabled: true,
    description: 'Normalize backward compatibility phrases',
  },
  {
    id: 'constraint-but-do-not',
    category: 'constraint',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'aggressive',
    pattern: /\bbut (?:please\s+)?do not\b/gi,
    replacement: '. No',
    enabled: true,
    description: 'Compress "but do not" constraint transitions',
  },
];
