import { CompressionRule } from '../../core/types';

export const fillerRules: CompressionRule[] = [
  {
    id: 'filler-greeting-start',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /^\s*(?:hello|hi|hey)\b(?:\s+there)?[!,.:\-\s]*/gim,
    replacement: '',
    enabled: true,
    description: 'Remove greeting starters at the beginning of a line or message',
  },
  {
    id: 'filler-let-say',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\blet(?:'s)?\s+say\b[:,]?\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "let say/let\'s say" filler phrase',
  },
  {
    id: 'filler-polite-request-prefix',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\b(?:can you please|could you please|would you please)\b\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove polite request prefixes',
  },
  {
    id: 'filler-polite-word',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\b(?:please|kindly)\b(?=[\s,.;!?]|$)\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove standalone polite filler words',
  },
  {
    id: 'filler-i-would-like-you-to',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bi would like (?:you )?to\b\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "I would like you to"',
  },
  {
    id: 'filler-i-need-you-to',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bi need you to\b\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "I need you to"',
  },
  {
    id: 'filler-i-want-you-to',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bi want you to\b\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "I want you to"',
  },
  {
    id: 'filler-what-i-want-is',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bwhat i want is\b\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "what I want is"',
  },
  {
    id: 'filler-feel-free-to',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bfeel free to\b\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "feel free to"',
  },
  {
    id: 'filler-make-sure-that',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bmake sure that\b\s*/gi,
    replacement: 'ensure ',
    enabled: true,
    description: 'Replace "make sure that" with "ensure"',
  },
  {
    id: 'filler-it-is-important-that',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bit is important that\b\s*/gi,
    replacement: 'ensure ',
    enabled: true,
    description: 'Replace "it is important that" with "ensure"',
  },
  {
    id: 'filler-in-order-to',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bin order to\b\s*/gi,
    replacement: 'to ',
    enabled: true,
    description: 'Replace "in order to" with "to"',
  },
  {
    id: 'filler-due-to-the-fact-that',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bdue to the fact that\b\s*/gi,
    replacement: 'because ',
    enabled: true,
    description: 'Replace "due to the fact that" with "because"',
  },
  {
    id: 'filler-i-want-to',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'aggressive',
    pattern: /\bi want to\b\s*/gi,
    replacement: '',
    enabled: false,
    description: 'Aggressively remove "I want to"',
  },
  {
    id: 'filler-hesitation-you-know',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\byou know\b/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "you know" hesitation filler'
  },
  {
    id: 'filler-hesitation-like',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\blike\b(?!\s+(?:a|an|the|i|you|he|she|it|we|they)(?:\s|$))/gi,
    replacement: '',
    enabled: true,
    description: 'Remove filler "like" (not simile preposition)'
  },
  {
    id: 'filler-hesitation-basically',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bbasically\b/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "basically" discourse filler'
  },
  {
    id: 'filler-hesitation-actually',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bactually\b(?=\s)/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "actually" filler at start of clause'
  },
  {
    id: 'filler-intensifier-very',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'aggressive',
    pattern: /\bvery\s+([a-z]+)/gi,
    replacement: '$1',
    enabled: true,
    description: 'Remove "very" intensifier'
  },
  {
    id: 'filler-intensifier-really',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'aggressive',
    pattern: /\breally\b\s+([a-z]+)/gi,
    replacement: '$1',
    enabled: true,
    description: 'Remove "really" intensifier before adjective'
  },
  {
    id: 'filler-intensifier-just',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bjust\b(?=\s+(?:a|one|the|this|that))/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "just" as softener/diminisher'
  },
  {
    id: 'filler-intensifier-quite',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'aggressive',
    pattern: /\bquite\b\s+([a-z]+)/gi,
    replacement: '$1',
    enabled: true,
    description: 'Remove "quite" intensifier'
  },
  {
    id: 'filler-softener-kind-of',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bkind of\b/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "kind of" softener'
  },
  {
    id: 'filler-softener-sort-of',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bsort of\b/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "sort of" softener'
  },
  {
    id: 'filler-conditional-if-possible',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bif possible\b/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "if possible" conditional filler'
  },
  {
    id: 'filler-conditional-in-case',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bin case\b(?!\s+(?:you|we|they))/gi,
    replacement: 'if',
    enabled: true,
    description: 'Replace "in case" with "if" (non-personal)'
  },
  {
    id: 'filler-redundancy-i-think',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bi think\b(?=\s)/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "I think" opinion filler'
  },
  {
    id: 'filler-redundancy-in-my-opinion',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bin my opinion\b/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "in my opinion"'
  },
  {
    id: 'filler-connector-having-said-that',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\b(?:having|that\s+)?said that\b/gi,
    replacement: 'however',
    enabled: true,
    description: 'Replace "having said that" with "however"'
  },
  {
    id: 'filler-connector-end-of-day',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bat the end of the day\b/gi,
    replacement: 'ultimately',
    enabled: true,
    description: 'Replace "at the end of the day" with "ultimately"'
  },
  {
    id: 'filler-repetition-the-the',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bthe\s+the\b/gi,
    replacement: 'the ',
    enabled: true,
    description: 'Fix accidental "the the" repetition'
  },
  {
    id: 'filler-um-uh',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\b(?:um|uh|er)\b/gi,
    replacement: '',
    enabled: true,
    description: 'Remove speech disfluencies like "um/uh/er"'
  },
  {
    id: 'filler-claude-sort-of',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bsort of\b/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "sort of" hedging (from write-good/textlint inspo)'
  },
  {
    id: 'filler-claude-kind-of',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bkind of\b/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "kind of" hedging'
  },
  {
    id: 'filler-claude-you-know',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\byou know[, ]?\b/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "you know" verbal tic'
  },
  {
    id: 'filler-claude-i-mean',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bi mean[, ]?\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "I mean" verbal tic'
  },
  {
    id: 'filler-claude-end-of-day',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bat the end of the day[, ]?\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "at the end of the day" cliche'
  },
  {
    id: 'filler-claude-needless-to-say',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bneedless to say[, ]?\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "needless to say" redundant'
  },
  {
    id: 'filler-claude-to-be-honest',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bto be (honest|frank|clear)[, ]?\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "to be honest/frank/clear" hedging'
  },
  {
    id: 'filler-claude-personally-i',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bpersonally[, ]?\s+i\b/gi,
    replacement: 'I',
    enabled: true,
    description: 'Remove "personally" redundant'
  },
  {
    id: 'filler-claude-in-my-opinion',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'balanced',
    pattern: /\bin my (personal\s+)?(opinion|view|experience)[, ]?\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "in my opinion/view" hedging'
  },
  {
    id: 'filler-claude-goes-without-saying',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bit goes without saying (that\s+)?/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "it goes without saying"'
  },
  {
    id: 'filler-claude-intents-purposes',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bfor all intents and purposes[, ]?\s*/gi,
    replacement: '',
    enabled: true,
    description: 'Remove "for all intents and purposes" cliche'
  },
  {
    id: 'filler-claude-this-point-time',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bat this point in time\b/gi,
    replacement: 'now',
    enabled: true,
    description: 'Replace "at this point in time" with "now"'
  },
  {
    id: 'filler-claude-event-that',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bin the event that\b/gi,
    replacement: 'if',
    enabled: true,
    description: 'Replace "in the event that" with "if"'
  },
  {
    id: 'filler-claude-daily-basis',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bon a (daily|regular|consistent) basis\b/gi,
    replacement: 'daily',
    enabled: true,
    description: 'Replace "on a daily/regular basis" with "daily"'
  },
  {
    id: 'filler-claude-close-proximity',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bin close proximity (to)?\b/gi,
    replacement: 'near',
    enabled: true,
    description: 'Replace "in close proximity" with "near"'
  },
  {
    id: 'filler-claude-prior-to',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bprior to\b/gi,
    replacement: 'before',
    enabled: true,
    description: 'Replace "prior to" with "before"'
  },
  {
    id: 'filler-claude-subsequent-to',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\bsubsequent to\b/gi,
    replacement: 'after',
    enabled: true,
    description: 'Replace "subsequent to" with "after"'
  },
  {
    id: 'filler-claude-utilize',
    category: 'filler',
    contentTypes: ['prose', 'mixed'],
    safetyLevel: 'safe',
    pattern: /\butili[sz]e(d|s)?\b/gi,
    replacement: 'use',
    enabled: true,
    description: 'Replace "utilize/utilised" with "use"'
  },
];
